# Written by Wes Oler, https://github.com/wes-o
# Distributed under terms of MIT License

# Developed and based on standard configuration file to create and activate a new conda environment
# https://mybinder.readthedocs.io/en/latest/using/config_files.html

# As of June 2022
# Changed explicit version numbers to match configuration
# defined at:
# https://github.com/jupyter/repo2docker/blob/master/repo2docker/buildpacks/conda/environment.yml


name: ds-jupyter-nb-view-base-environment
channels:
  - conda-forge
dependencies:
  - cython
  - jupyterlab>2
  - ipykernel>5.1
  - ipywidgets==7.7.0
  - line_profiler
  - matplotlib>3
  - notebook==6.4.10
  - numpy
  - nodejs=14
  - pillow
  - plotly
  - python=3.7
  - pip
  - pip:
    - jupyterlab_latex
    - nbgitpuller
    - sphinx-gallery
    - pandas
